import {
  Archive, Bold, ChevronDown, ChevronLeft, ChevronRight, Camera, Check, Clock, Code, Copy, Database, Download, Eye,
  Files, Globe, Hash, Image, Italic, KeyRound, Keyboard, LayoutGrid, Link, List, ListOrdered, ListTodo, Lock, LogOut,
  MessageCircle, MessageSquareText, Moon, Palette, PenLine, Pin, Plus, Quote, RefreshCw, Rss, Search,
  SeparatorHorizontal, Settings, Shield, SlidersHorizontal, Sparkles, Sun, Trash2, TriangleAlert, Type, Upload, User,
  Users, WandSparkles, X, Zap,
} from 'lucide';
import { iconSet } from '../../utils/lucide';

/** 移动后台图标：名字 → Lucide 标准图标（SVG 内部片段）；选中态由父级加粗描边 */
export const ICONS = iconSet({
  grid: LayoutGrid,
  docs: Files,
  image: Image,
  user: User,
  bubble: MessageSquareText,
  plus: Plus,
  back: ChevronLeft,
  chev: ChevronRight,
  chevd: ChevronDown,
  close: X,
  search: Search,
  list: List,
  olist: ListOrdered,
  task: ListTodo,
  type: Type,
  rss: Rss,
  clock: Clock,
  hash: Hash,
  key: KeyRound,
  upload: Upload,
  pen: PenLine,
  camera: Camera,
  globe: Globe,
  gear: Settings,
  palette: Palette,
  archive: Archive,
  out: LogOut,
  check: Check,
  bold: Bold,
  italic: Italic,
  quote: Quote,
  code: Code,
  link: Link,
  hr: SeparatorHorizontal,
  eye: Eye,
  bolt: Zap,
  sun: Sun,
  moon: Moon,
  pin: Pin,
  trash: Trash2,
  sliders: SlidersHorizontal,
  copy: Copy,
  spark: Sparkles,
  alert: TriangleAlert,
  lock: Lock,
  shield: Shield,
  comment: MessageCircle,
  users: Users,
  database: Database,
  refresh: RefreshCw,
  down: Download,
  wand: WandSparkles,
  keyboard: Keyboard,
});

export type IconName = keyof typeof ICONS;
