import {
  Archive, ArrowLeft, ArrowRight, Bold, Calendar, Check, ChevronDown, Clock, Code, Copy, Cpu, Crop, DoorOpen,
  Download, Ellipsis, ExternalLink, Eye, EyeOff, Feather, FileCode, FileText, Flag, GitBranch, Globe, GripVertical,
  Hash, Heart, Image, Info, Italic, KeyRound, LayoutDashboard, LayoutGrid, Layers, Link, List, ListOrdered, ListTodo,
  Lock, LogOut, Mail, MessageSquare, Minus, Moon, Palette, PanelRight, PenLine, Pin, Play, Plus, Quote, Redo2,
  RefreshCw, Reply, Search, Send, SeparatorHorizontal, Settings, Shield, Shrink, Smile, Sparkles, SquareCode,
  SquareTerminal, Strikethrough, Sun, Table, Trash2, Undo2, Upload, User, Users, WandSparkles, X, ZoomIn,
} from 'lucide';
import { iconSet } from '../../../utils/lucide';

/** Studio 图标：名字 → Lucide 标准图标（SVG 内部片段） */
export const ICONS: Record<string, string> = iconSet({
  sun: Sun,
  moon: Moon,
  pen: PenLine,
  doc: FileText,
  feather: Feather,
  image: Image,
  user: User,
  palette: Palette,
  key: KeyRound,
  archive: Archive,
  message: MessageSquare,
  users: Users,
  settings: Settings,
  plus: Plus,
  minus: Minus,
  search: Search,
  grid: LayoutGrid,
  list: List,
  arrowR: ArrowRight,
  arrowL: ArrowLeft,
  chevronD: ChevronDown,
  check: Check,
  x: X,
  more: Ellipsis,
  pin: Pin,
  clock: Clock,
  eye: Eye,
  eyeOff: EyeOff,
  lock: Lock,
  link: Link,
  bold: Bold,
  italic: Italic,
  strike: Strikethrough,
  quote: Quote,
  code: Code,
  codeBlock: SquareCode,
  ul: List,
  ol: ListOrdered,
  task: ListTodo,
  table: Table,
  hr: SeparatorHorizontal,
  undo: Undo2,
  redo: Redo2,
  collage: LayoutDashboard,
  markdown: FileCode,
  upload: Upload,
  download: Download,
  trash: Trash2,
  copy: Copy,
  refresh: RefreshCw,
  panel: PanelRight,
  cpu: Cpu,
  crop: Crop,
  grip: GripVertical,
  external: ExternalLink,
  calendar: Calendar,
  mail: Mail,
  compress: Shrink,
  globe: Globe,
  door: DoorOpen,
  branch: GitBranch,
  shield: Shield,
  reply: Reply,
  flag: Flag,
  send: Send,
  smile: Smile,
  logout: LogOut,
  sparkle: Sparkles,
  play: Play,
  terminal: SquareTerminal,
  info: Info,
  layers: Layers,
  heart: Heart,
  hash: Hash,
  wand: WandSparkles,
  zoomIn: ZoomIn,
});
