import {
  siAndroid,
  siAngular,
  siAnsible,
  siApachekafka,
  siApple,
  siArchlinux,
  siArduino,
  siAstro,
  siBlender,
  siBun,
  siC,
  siCaddy,
  siClaude,
  siClickhouse,
  siCloudflare,
  siCplusplus,
  siCss,
  siDart,
  siDebian,
  siDeno,
  siDjango,
  siDocker,
  siDotnet,
  siDuckdb,
  siElasticsearch,
  siElectron,
  siElixir,
  siEsbuild,
  siEslint,
  siExpress,
  siFastapi,
  siFigma,
  siFirebase,
  siFlask,
  siFlutter,
  siGin,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGnubash,
  siGo,
  siGodotengine,
  siGrafana,
  siGraphql,
  siHaskell,
  siHomebrew,
  siHono,
  siHtml5,
  siHuggingface,
  siHugo,
  siJavascript,
  siJetbrains,
  siJulia,
  siJupyter,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLatex,
  siLinux,
  siLua,
  siMariadb,
  siMarkdown,
  siMongodb,
  siMysql,
  siNeovim,
  siNetlify,
  siNextdotjs,
  siNginx,
  siNixos,
  siNodedotjs,
  siNotion,
  siNpm,
  siNuxt,
  siObsidian,
  siOllama,
  siOpenjdk,
  siPhp,
  siPinia,
  siPnpm,
  siPostgresql,
  siPrettier,
  siPrisma,
  siPrometheus,
  siPython,
  siPytorch,
  siRabbitmq,
  siRaspberrypi,
  siReact,
  siRedis,
  siRuby,
  siRubyonrails,
  siRust,
  siSass,
  siScala,
  siSketch,
  siSolid,
  siSpringboot,
  siSqlite,
  siSupabase,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTauri,
  siTensorflow,
  siTerraform,
  siTypescript,
  siTypst,
  siUbuntu,
  siUnity,
  siUnrealengine,
  siVercel,
  siVim,
  siVite,
  siVitest,
  siVuedotjs,
  siWebassembly,
  siWebpack,
  siWordpress,
  siYarn,
  siZig,
} from 'simple-icons';
import { brandOf, type Brand } from './brands';

/**
 * 技术栈品牌图标注册表：取自离线安装的 simple-icons（官方 24 网格实心路径 + 品牌色 hex）。
 * 键即 StackItem.icon 的取值；keywords 供后台下拉搜索（别名 / 缩写），不显示。
 * 新增：从 simple-icons 按名引入（si + 标题驼峰，如 siNodedotjs），在 TECH 里加一行。
 */
export interface Tech extends Brand {
  keywords: string;
}

const x = (label: string, icon: Parameters<typeof brandOf>[1], keywords = ''): Tech => ({ ...brandOf(label, icon), keywords });

export const TECH: Record<string, Tech> = {
  go: x('Go', siGo, 'golang'),
  typescript: x('TypeScript', siTypescript, 'ts'),
  javascript: x('JavaScript', siJavascript, 'js ecmascript'),
  python: x('Python', siPython, 'py'),
  rust: x('Rust', siRust, 'rs'),
  java: x('Java', siOpenjdk, 'openjdk jdk'),
  kotlin: x('Kotlin', siKotlin, 'kt'),
  swift: x('Swift', siSwift),
  c: x('C', siC, 'clang'),
  cpp: x('C++', siCplusplus, 'cplusplus cpp'),
  dotnet: x('.NET', siDotnet, 'csharp c# dotnet'),
  php: x('PHP', siPhp),
  ruby: x('Ruby', siRuby, 'rb'),
  dart: x('Dart', siDart),
  lua: x('Lua', siLua),
  zig: x('Zig', siZig),
  elixir: x('Elixir', siElixir),
  haskell: x('Haskell', siHaskell),
  scala: x('Scala', siScala),
  julia: x('Julia', siJulia),
  bash: x('Bash', siGnubash, 'shell sh gnubash'),
  wasm: x('WebAssembly', siWebassembly, 'wasm'),
  markdown: x('Markdown', siMarkdown, 'md'),
  vue: x('Vue.js', siVuedotjs, 'vue3 vuejs'),
  react: x('React', siReact, 'reactjs'),
  svelte: x('Svelte', siSvelte, 'sveltekit'),
  angular: x('Angular', siAngular),
  solid: x('Solid', siSolid, 'solidjs'),
  astro: x('Astro', siAstro),
  nextjs: x('Next.js', siNextdotjs, 'next'),
  nuxt: x('Nuxt', siNuxt, 'nuxtjs'),
  vite: x('Vite', siVite),
  vitest: x('Vitest', siVitest),
  tailwindcss: x('Tailwind CSS', siTailwindcss, 'tailwind'),
  sass: x('Sass', siSass, 'scss'),
  html5: x('HTML5', siHtml5, 'html'),
  css: x('CSS', siCss, 'css3'),
  pinia: x('Pinia', siPinia),
  electron: x('Electron', siElectron),
  tauri: x('Tauri', siTauri),
  flutter: x('Flutter', siFlutter),
  nodejs: x('Node.js', siNodedotjs, 'node'),
  deno: x('Deno', siDeno),
  bun: x('Bun', siBun),
  express: x('Express', siExpress),
  hono: x('Hono', siHono),
  gin: x('Gin', siGin),
  django: x('Django', siDjango),
  flask: x('Flask', siFlask),
  fastapi: x('FastAPI', siFastapi),
  spring: x('Spring Boot', siSpringboot, 'spring'),
  laravel: x('Laravel', siLaravel),
  rails: x('Ruby on Rails', siRubyonrails, 'rails ror'),
  graphql: x('GraphQL', siGraphql),
  prisma: x('Prisma', siPrisma),
  sqlite: x('SQLite', siSqlite),
  postgresql: x('PostgreSQL', siPostgresql, 'postgres pg'),
  mysql: x('MySQL', siMysql),
  mariadb: x('MariaDB', siMariadb),
  redis: x('Redis', siRedis),
  mongodb: x('MongoDB', siMongodb, 'mongo'),
  elasticsearch: x('Elasticsearch', siElasticsearch, 'es'),
  clickhouse: x('ClickHouse', siClickhouse),
  duckdb: x('DuckDB', siDuckdb),
  supabase: x('Supabase', siSupabase),
  firebase: x('Firebase', siFirebase),
  docker: x('Docker', siDocker),
  kubernetes: x('Kubernetes', siKubernetes, 'k8s'),
  nginx: x('NGINX', siNginx),
  caddy: x('Caddy', siCaddy),
  cloudflare: x('Cloudflare', siCloudflare),
  vercel: x('Vercel', siVercel),
  netlify: x('Netlify', siNetlify),
  terraform: x('Terraform', siTerraform),
  ansible: x('Ansible', siAnsible),
  grafana: x('Grafana', siGrafana),
  prometheus: x('Prometheus', siPrometheus),
  rabbitmq: x('RabbitMQ', siRabbitmq),
  kafka: x('Apache Kafka', siApachekafka, 'kafka'),
  git: x('Git', siGit),
  github: x('GitHub', siGithub),
  gitlab: x('GitLab', siGitlab),
  githubactions: x('GitHub Actions', siGithubactions, 'ci actions'),
  pnpm: x('pnpm', siPnpm),
  npm: x('npm', siNpm),
  yarn: x('Yarn', siYarn),
  webpack: x('Webpack', siWebpack),
  esbuild: x('esbuild', siEsbuild),
  eslint: x('ESLint', siEslint),
  prettier: x('Prettier', siPrettier),
  linux: x('Linux', siLinux),
  ubuntu: x('Ubuntu', siUbuntu),
  debian: x('Debian', siDebian),
  archlinux: x('Arch Linux', siArchlinux, 'arch'),
  nixos: x('NixOS', siNixos, 'nix'),
  apple: x('Apple', siApple, 'macos mac ios'),
  android: x('Android', siAndroid),
  homebrew: x('Homebrew', siHomebrew, 'brew'),
  neovim: x('Neovim', siNeovim, 'nvim'),
  vim: x('Vim', siVim),
  jetbrains: x('JetBrains', siJetbrains, 'idea goland'),
  figma: x('Figma', siFigma),
  sketch: x('Sketch', siSketch),
  blender: x('Blender', siBlender),
  unity: x('Unity', siUnity),
  godot: x('Godot', siGodotengine, 'godotengine'),
  unreal: x('Unreal Engine', siUnrealengine, 'ue'),
  pytorch: x('PyTorch', siPytorch, 'torch'),
  tensorflow: x('TensorFlow', siTensorflow, 'tf'),
  jupyter: x('Jupyter', siJupyter),
  huggingface: x('Hugging Face', siHuggingface, 'hf'),
  ollama: x('Ollama', siOllama),
  claude: x('Claude', siClaude, 'anthropic'),
  obsidian: x('Obsidian', siObsidian),
  notion: x('Notion', siNotion),
  latex: x('LaTeX', siLatex, 'tex'),
  typst: x('Typst', siTypst),
  hugo: x('Hugo', siHugo),
  wordpress: x('WordPress', siWordpress, 'wp'),
  raspberrypi: x('Raspberry Pi', siRaspberrypi, 'rpi'),
  arduino: x('Arduino', siArduino),
};

const norm = (s: string): string => s.toLowerCase().replace(/[\s._\-/]/g, '');

/** 名称 / 别名 → 键（猜测用） */
const INDEX = new Map<string, string>();
for (const [key, tech] of Object.entries(TECH)) {
  for (const w of [key, tech.label, ...tech.keywords.split(' ')]) if (w && !INDEX.has(norm(w))) INDEX.set(norm(w), key);
}

/**
 * 按名称猜品牌图标（旧数据没有 icon 字段时由 migrate.ts 在读取时补上）：
 * 「Vue 3」→ vue、「Node.js」→ nodejs、「C++」→ cpp；猜不到返回空串（显示文字徽标）。
 */
export function guessTech(name: string): string {
  const n = norm(name);
  if (!n) return '';
  return INDEX.get(n) ?? INDEX.get(n.replace(/\d+$/, '')) ?? '';
}

/**
 * 徽标着色：近黑（Rust / Next.js…）与近白（Unity…）的品牌色总有一种主题下看不清，改用正文色；
 * 其余返回原色。空值返回 undefined，交给调用方回落主题色。
 */
export function techInk(color: string | undefined): string | undefined {
  const m = /^#([0-9a-f]{6})$/i.exec((color ?? '').trim());
  if (!m) return color || undefined;
  const n = parseInt(m[1], 16);
  const lum = 0.299 * ((n >> 16) & 255) + 0.587 * ((n >> 8) & 255) + 0.114 * (n & 255);
  return lum < 48 || lum > 225 ? 'var(--text)' : `#${m[1]}`;
}
